name: Lint and Quality Checks

on: [push]

jobs:
  lint-and-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Run Black (formatter check)
        uses: psf/black@stable
        with:
          options: "--check --verbose -t py310"
          src: "./openodia ./tests"

      - name: Lint with Flake8
        run: poetry run flake8 . --count --show-source --statistics

      - name: Run MyPy (static type checking)
        run: poetry run mypy openodia tests --ignore-missing-imports

      - name: Security Analysis with Bandit
        run: |
          mkdir -p ci-logs
          poetry run bandit -r -lll -f txt -o ci-logs/bandit.log ./openodia ./tests

      - name: Archive bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: ci-logs/bandit.log
