name: Test and Release 
on:
  push:
    branches: [ main ]
  
jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Configure uv & Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install uv && uv sync --all-extras
    
    - name: View uv version
      run: uv --version
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        uv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Security Analysis with bandit
      run: |
        # stop pipeline if level 3 vulnerability found
        uv run bandit -r -lll ./openodia ./tests
    - name: Test with pytest
      run: |
        uv run python -m pytest -v tests
    
  Release:
    needs: Quality
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v7.33.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository_username: ${{ secrets.PYPI_USER }}
          repository_password: ${{ secrets.PYPI_SECRET }}
